# Generated by Django 3.0.7 on 2020-07-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagecarouselimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title',
        ),
    ]
